<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>Projet Events JS</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
        <link href="style.css" rel="stylesheet" />
    </head>
    <body>
        <h1>INFORMATION</h1>
        
        <form>
            <div class="form">
                
           <label for="Nom" class="lnom" >Nom</label>
            <input type="text" name="nom" class="cnom"/>
            
            <label for="Prenom" class="lprenom">Prenom</label>
            <input type="text" name="prenom" class="cprenom"/>
            
            <label for="email" class="lprenom">Email</label>
            <input type="email" name="email"/>
            
            <label for="telephone" class="ltelephone">Télephone</label>
            <input type="number" name="telephone"/>
            
            <label for="linkedln" class="llinkedln">Linkedln</label>
            <input type="text" name="linkedln"/>
            
            <label for="github" class="lgithub">Github</label>
            <input type="text" name="github"/>
            
            <label for="biographie" class="lbiographie">Biographie</label>
            <textarea name="textarea" rows="10" cols="50"></textarea>
            
            <label for="loisir" class="lloisir">Loisir1</label>
            <input type="text" name="loisir"/>
            
             <label for="loisir" class="lloisir ">Loisir2</label>
            <input type="text" name="loisir2"/>
            
             <label for="loisir" class="lloisir3">Loisir3</label>
            <input type="text" name="loisir3"/>
            
             <label for="loisir" class="lloisir">Loisir4</label>
            <input type="text" name="loisir4"/>
            
            <h2>Langues</h2>
            
            <fieldset>

            <div>
              <input type="checkbox" id="francais" name="francais" checked>
              <label for="francais">Français</label>
            </div>

            <div>
              <input type="checkbox" id="anglais" name="anglais">
              <label for="horns">Anglais</label>
            </div>
            <div>
                <input type="checkbox" name="arabe" id="arabe"/>
                <label for="arabe">Arabe</label>
            </div>
            <div>
                <input type="checkbox" name="breton" id="breton"/>
                <label for="breton">Breton</label>
                
            </div>
            <div>
                <input type="checkbox" name="espagnol" id="espagnol"/>
                <label for="espagnol">Espagnol</label>
            </div>
</fieldset>
            
            <button class="favorite styled" type="button">
                
                ENVOYER
            </button>
            
             </div>
        </form>
        
        
    </body>
       
            
</html>